name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    name: Packer Format and Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      - name: creating zip
        run: |
            sudo apt-get install zip -y
            zip webapp.zip .
            
      - name: Run packer fmt check
        run: |
            packer init .

      - name: Run packer fmt check
        run: |
          packer fmt -check .
          if [ $? -ne 0 ]; then
            echo "Packer fmt failed."
            exit 1
          fi

      - name: Run packer validate
        run: |
          packer validate .
          if [ $? -ne 0 ]; then
            echo "Packer validate failed."
            exit 1
          fi
