name: Test Webapp
 
# Run this workflow on pull requests to main branch
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Webapp Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.13'

      - name: Install dependencies  
        run: |
            sudo apt install -y python3-pip pkg-config libmysqlclient-dev

      - name: Install required libraries from requirements.txt
        run: |
            pip install -r requirements.txt

      - name: Configure MySQL
        env:
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
            sudo mysql -u root -e "CREATE USER '${{ secrets.MYSQL_USER }}'@'localhost' IDENTIFIED BY '${{ secrets.MYSQL_PASSWORD }}';"
            sudo mysql -u root -e "GRANT ALL PRIVILEGES ON test_${{ secrets.DB_NAME }}.* TO '${{ secrets.MYSQL_USER }}'@'localhost' WITH GRANT OPTION;"

      - name: Create .env file
        env:
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
            echo "TEST_DATABASE_URL=mysql://$MYSQL_USER:$MYSQL_PASSWORD@localhost/test_$DB_NAME" > .env
            echo "DATABASE_URL=mysql://$MYSQL_USER:$MYSQL_PASSWORD@localhost/$DB_NAME" >> .env

      - name: Run tests
        run: |
            python -m pytest tests/
        
    