name: Test Webapp
 
# Run this workflow on pull requests to main branch
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Webapp Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.13'

      - name: Install dependencies  
        run: |
            sudo apt install -y python3-pip pkg-config libmysqlclient-dev

      - name: Install required libraries from requirements.txt
        run: |
            pip install -r requirements.txt

      - name: Configure MySQL
        env:
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DEFAULT_USER: ${{ secrets.DEFAULT_USER }}
          DEFAULT_PASS: ${{ secrets.DEFAULT_PASS }}
          DB_HOST: ${{ secrets.HOST }}
        run: |
            service mysql start
            mysql -u $DEFAULT_USER -p$DEFAULT_PASS -e"CREATE USER '$MYSQL_USER'@'$DB_HOST' IDENTIFIED BY '$MYSQL_PASSWORD';"
            mysql -u $DEFAULT_USER -p$DEFAULT_PASS -e"GRANT ALL PRIVILEGES ON test_$DB_NAME.* TO '$MYSQL_USER'@'$DB_HOST' WITH GRANT OPTION;"

      - name: Create .env file
        env:
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
            echo "TEST_DATABASE_URL=mysql://$MYSQL_USER:$MYSQL_PASSWORD@localhost/test_$DB_NAME" > .env
            echo "DATABASE_URL=mysql://$MYSQL_USER:$MYSQL_PASSWORD@localhost/$DB_NAME" >> .env

      - name: Run tests
        run: |
            python -m pytest tests/
        
    